// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-arRmqxZ2vG8rwB1oTK6nemUxAo60-P8',
    appId: '1:175116693291:web:841e94f09878a82a9adf6e',
    messagingSenderId: '175116693291',
    projectId: 'mynotes-flutter-m',
    authDomain: 'mynotes-flutter-m.firebaseapp.com',
    storageBucket: 'mynotes-flutter-m.appspot.com',
    measurementId: 'G-H4G1J78PY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkep2asgItgZz_nWa-Rj7AW0BXt5ZrCqg',
    appId: '1:175116693291:android:d10ad381d7c96b819adf6e',
    messagingSenderId: '175116693291',
    projectId: 'mynotes-flutter-m',
    storageBucket: 'mynotes-flutter-m.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0NEIfzl28ewUKzbkLsvzAPCHQ_7ElpNg',
    appId: '1:175116693291:ios:97984d28516b11f49adf6e',
    messagingSenderId: '175116693291',
    projectId: 'mynotes-flutter-m',
    storageBucket: 'mynotes-flutter-m.appspot.com',
    iosClientId: '175116693291-b3erp567gc3ab2l7tur7c4i8kjc3pq81.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0NEIfzl28ewUKzbkLsvzAPCHQ_7ElpNg',
    appId: '1:175116693291:ios:97984d28516b11f49adf6e',
    messagingSenderId: '175116693291',
    projectId: 'mynotes-flutter-m',
    storageBucket: 'mynotes-flutter-m.appspot.com',
    iosClientId: '175116693291-b3erp567gc3ab2l7tur7c4i8kjc3pq81.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNoteApp',
  );
}
